### PR TITLE
More robust URI parsing in M3U files

### LINKED ISSUE #277: FFMPEG No such file or directory but ffmeg is found
**telly release with the issue:**
telly is preparing to go live (version=1.1.0.8, branch=dev, revision=96424a4719f33de9c1b66d8d2186e0452e45a234)

**Last working telly release (if known):**
-

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
Debian 10 (LXC)

**Description of problem:**
ffmpeg is found and started bu last message in log is "No such file or directory" (see log)

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
ffmpeg=true (see log)

**Command line used to run telly [if applicable]:**
none

**telly or docker log:**
time="2020-07-31T10:01:28+02:00" level=info msg="telly is preparing to go live (version=1.1.0.8, branch=dev, revision=96424a4719f33de9c1b66d8d2186e0452e45a234)"
time="2020-07-31T10:01:28+02:00" level=debug msg="Build context (go=go1.12.17, user=root@7abd9a6a6502, date=20200704-05:23:36)"
time="2020-07-31T10:01:28+02:00" level=debug msg="Loaded configuration {\n    \"config\": {\n        \"file\": \"\"\n    },\n    \"discovery\": {\n        \"device-auth\": \"telly123\",\n        \"device-firmware-name\": \"hdhomeruntc_atsc\",\n        \"device-firmware-version\": \"20150826\",\n        \"device-friendly-name\": \"telly\",\n        \"device-id\": \"12345678\",\n        \"device-manufacturer\": \"Silicondust\",\n        \"device-model-number\": \"HDTC-2US\",\n        \"device-uuid\": \"12345678-AE2A-4E54-BBC9-33AF7D5D6A92\",\n        \"ssdp\": true\n    },\n    \"filter\": {\n        \"regex\": \".*\",\n        \"regex-inclusive\": false\n    },\n    \"iptv\": {\n        \"ffmpeg\": true,\n        \"playlist\": \"\",\n        \"starting-channel\": 10000,\n        \"streams\": 10,\n        \"xmltv-channels\": true\n    },\n    \"log\": {\n        \"level\": \"debug\",\n        \"requests\": true\n    },\n    \"source\": [\n        {\n            \"M3U\": \"/home/telly/playlistTV_rewrite.m3u\",\n            \"Name\": \"\",\n            \"Provider\": \"Custom\"\n        }\n    ],\n    \"version\": false,\n    \"web\": {\n        \"base-address\": \"192.168.178.226:6077\",\n        \"listen-address\": \"0.0.0.0:6077\"\n    }\n}"
time="2020-07-31T10:01:28+02:00" level=info msg="Loading M3U from /home/telly/playlistTV_rewrite.m3u"
time="2020-07-31T10:01:28+02:00" level=debug msg="These channels (75) passed the filter and successfully parsed: ....
time="2020-07-31T10:01:28+02:00" level=debug msg="These channels (0) did NOT pass the filter: "
time="2020-07-31T10:01:28+02:00" level=info msg="Loaded 75 channels into the lineup from "
time="2020-07-31T10:01:28+02:00" level=debug msg="creating device xml"
time="2020-07-31T10:01:28+02:00" level=debug msg="creating webserver routes"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /metrics                  --> github.com/tellytv/telly/internal/go-gin-prometheus.prometheusHandler.func1 (4 handlers)
[GIN-debug] GET    /                         --> main.deviceXML.func1 (4 handlers)
[GIN-debug] GET    /discover.json            --> main.discovery.func1 (4 handlers)
[GIN-debug] GET    /lineup_status.json       --> main.serve.func1 (4 handlers)
[GIN-debug] POST   /lineup.post              --> main.serve.func2 (4 handlers)
[GIN-debug] GET    /device.xml               --> main.deviceXML.func1 (4 handlers)
[GIN-debug] GET    /lineup.json              --> main.serveLineup.func1 (4 handlers)
[GIN-debug] GET    /lineup.xml               --> main.serveLineup.func1 (4 handlers)
[GIN-debug] GET    /auto/:channelID          --> main.stream.func1 (4 handlers)
[GIN-debug] GET    /epg.xml                  --> main.xmlTV.func2 (4 handlers)
[GIN-debug] GET    /debug.json               --> main.serve.func3 (4 handlers)
time="2020-07-31T10:01:28+02:00" level=debug msg="Advertising telly as telly (12345678-AE2A-4E54-BBC9-33AF7D5D6A92)"
[GIN-debug] GET    /manage/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
[GIN-debug] HEAD   /manage/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (4 handlers)
time="2020-07-31T10:01:28+02:00" level=info msg="telly is live and on the air!"
time="2020-07-31T10:01:28+02:00" level=info msg="Broadcasting from http://192.168.178.226:6077/"
time="2020-07-31T10:01:28+02:00" level=info msg="EPG URL: http://192.168.178.226:6077/epg.xml"
time="2020-07-31T10:01:28+02:00" level=info msg="Lineup JSON: http://192.168.178.226:6077/lineup.json"
[GIN-debug] Listening and serving HTTP on 0.0.0.0:6077
time="2020-07-31T10:01:36+02:00" level=info msg="Serving channel number 10006"
time="2020-07-31T10:01:36+02:00" level=info msg="Remuxing stream with ffmpeg"
time="2020-07-31T10:01:36+02:00" level=info msg="ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers"
time="2020-07-31T10:01:36+02:00" level=info msg="  built with gcc 8 (Debian 8.3.0-6)"
time="2020-07-31T10:01:36+02:00" level=info msg="  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavutil      56. 22.100 / 56. 22.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavcodec     58. 35.100 / 58. 35.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavformat    58. 20.100 / 58. 20.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavdevice    58.  5.100 / 58.  5.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavfilter     7. 40.101 /  7. 40.101"
time="2020-07-31T10:01:36+02:00" level=info msg="  libavresample   4.  0.  0 /  4.  0.  0"
time="2020-07-31T10:01:36+02:00" level=info msg="  libswscale      5.  3.100 /  5.  3.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libswresample   3.  3.100 /  3.  3.100"
time="2020-07-31T10:01:36+02:00" level=info msg="  libpostproc    55.  3.100 / 55.  3.100"
time="2020-07-31T10:01:36+02:00" level=info msg=": No such file or directory"
time="2020-07-31T10:01:36+02:00" level=info msg="Stopped streaming 10006"
time="2020-07-31T10:01:36+02:00" level=info msg="Stopped streaming 10006"
http: superfluous response.WriteHeader call from github.com/gin-gonic/gin.(*responseWriter).WriteHeaderNow (response_writer.go:70)

**Additional information:**
ffmpeg is working fine from command line

### PR DESCRIPTION
**Pull request by mulbc**
Adds: 

* debug output for how we execute ffmpeg 
* Better URI parsing in M3u files to support rtsp URIs (for FritzBox boxes)

This should Resolve #277

### CODE REVIEW

**Comment by chazlarson** [comment]
Does this work if ffmpeg is disabled?  In that case it's just going to pass the URL to Plex, and I don't think Plex handles rtsp URLs.

**Comment by mulbc** [comment]
Indeed, rtsp links won't work without ffmpeg, but _with_ ffmpeg this would work. In my opinion though, the parser shouldn't limit URIs to HTTP and UDP links, but accept whatever URI is in there. Even with HTTP and UDP links we don't know if that would work without ffmpeg (the reason why we have the option I assume)

The main reason for me to use Telly is to Proxy the LiveTV that is offered by my FritzBox to Plex. Plex has a builtin beta for doing this directly, but it's rather instable. Going via Telly appears to be a bit more stable.
But I need the change in this PR in order to use my FritzBox for this... Because the FritzBox only offers rtsp links

**Comment by chazlarson** [comment]
The right answer then is to broaden the acceptance of URL schemes to accept those that work with the current config, not open the door to any URLs at all without regard for whether the target environment accepts them.

**Comment by mulbc** [comment]
What I tried to say is that the protocol isn't too important in the decision if Plex supports it right now (or in the future). Even without ffmpeg and directing Plex directly to the rtsp link, it doesn't fail immediately. Therefore I assume, Plex generally supports rtsp, but not this particular video format or container.

Therefore even without this PR we could have HTTP or UDP links that Plex wouldn't be able to handle without ffmpeg.

So my reasoning:
With this PR, people with a FritzBox will be able to use this if they enable ffmpeg. Without this PR, there is no way for them to use their FritzBox.

One thing that I could offer: If people have URIs that are not http or udp AND don't have ffmpeg enabled, we could print a warning to the log stating that ffmpeg will most likely be needed.

**Comment by chazlarson** [comment]
Fair point, but my next question would be why not add `rtsp` rather than just accepting whatever?  Of course, letting telly accept `rtsp` links adds functionality in this case and enables use of this device, but why is the solution to accept any URL at all?  I typically prefer enabling just what needs to be enabled, rather than throwing errors after the fact about things that perhaps should have been blocked before attempting.

Rather like websites that let you enter a new password, only to tell you **afterwards** that it doesn't meet some requirement.

**Comment by mulbc** [comment]
I didn't see a reason why we should limit it to the protocols we anticipate right now, when there are many more possible protocols out there. Especially with the mighty ffmpeg we can probably support a fair amount of protocols.

If you really only want to have http, udp and rtsp protocols, I can do that, but then I'd rather not have that logic in the m3u parser, but later in the actual main code.

Let me know what you prefer.

**Comment by chazlarson** [comment]
For me it's a not a matter of whether or not ffmpeg potentially supports different protocols.  It's more that the two that are currently allowed are typically supported **with or without** ffmpeg.  Sure, there may be some specific http or udp links that don't work with Plex directly, but in the case of rtsp, it *requires* ffmpeg, as would many in the list of possible protocols you mention.  In my opinion, if telly is going to allow a protocol that *requires* ffmpeg be turned on, it should enforce that requirement.

Personally I would rather the behavior be "if the m3u contains a protocol that requires ffmpeg be enabled but ffmpeg is **not** enabled, exit with a descriptive error", similar to how it behaves with excessive numbers of channels.  Allowing it through only for the Plex black box to fail with a vague but totally predictable error later is bound to result in user confusion as to why it's failing.

That's also why I'd prefer to limit the list to known good protocols that are actually seen in the the wild.  If everything gets let through, now you've got users wondering why this file:// or whatever link isn't working when there's no expectation it even should.

**Comment by mulbc** [comment]
I implemented a check in lineup.go to check if ffmpeg is enabled for URIs that are neither HTTP or UDP (it will issue a warning otherwise)
I think this is what you wanted, right?

**Pull request merged**
