### PR TITLE
new docker architecture 

### PR DESCRIPTION
**Pull request by Nottt**
Main improvements:

1. Auto update to latest version
2. Using pre-compiled files instead of building locally
3. Always use the latest ffmpeg version
4. PGID and PUID variables
5. Create the configuration file dynamically with variables while still allowing persistent customization
6. TZ variable for Windows and OS X users sync time with host

### CODE REVIEW

**Comment by robbiet480** [comment]
Looks like there are a lot of unassociated changes. Did you start your branch from the latest version of the `master` branch?

**Comment by Nottt** [comment]
Yes. It's not clean, but me and chazlarson tested it, should be fine. But if we desired we can create a clean branch and clean pull

**Comment by chazlarson** [comment]
I believe I created the branch here from dev, so I think the issues are my fault.  I just created a new branch from master and started a new pull request and none of those extraneous changes are in it.  I'll start a new pull request on that branch, which is currently named "docker-experimental-2".

**Comment by chazlarson** [comment]
OK, that new one [240] is much cleaner, but it has my name on it.  Nottt, if you want you can do another pull request to that branch to replace this one and the test one I just did.  OR we can just use the new one.  Doesn't make any difference to me.

**Comment by Nottt** [comment]
I am not sure you can truly rename a branch in github. I think you'll have to delete that one and create another one regardless (like I saw [here ](https://stackoverflow.com/questions/9524933/renaming-a-branch-in-github) when I tried). 

So if you have to create another one anyway I'd prefer if you just delete those 2 here, close the pull requests, create a new one clean and then I'll make the pull request again no problem. But either way I'm fine. 

Also what do you think of the branch being called docker? That way we can pull with `tellytv/docker` which is short, intuitive and the current dockers (ex: `tellytv/telly:dev-ffmpeg`) will not be affected while makes for a smooth transition. 

You can tell people wanting to try the new docker to use `tellytv/docker`, and when you feel confident, you phase out the others and you can have `tellytv/docker-dev` branch for `tellytv/docker:dev` tag in the docker hub. 

But that would just be my suggestions, up to you guys ^^

**Comment by chazlarson** [comment]
OK, I closed my pull request on the `docker-experimental-2` branch and renamed it `docker`.

**Pull request closed without merging**
