### PR TITLE
[WIP] Add SSDP support

### PR DESCRIPTION
**Pull request by HazCod**
Add uPNP/SSDP support, so that discovery and heartbeat of telly works.
This will fix the 'tuner not available' errors.

### CODE REVIEW

**Comment by tombowditch** [comment]
Looking good so far, will take a look myself later.

**Comment by lellimecnar** [comment]
I'm pretty sure this is the issue I'm having. I'm looking forward to this fix! 😁

**Comment by handyhelp** [comment]
any news about this issue? I get the error too tuner not found on my synology nas 😊

**Comment by HazCod** [comment]
This needs to be done in a goroutine, which honestly I am not familiar with.
You worked with it before @tombowditch ?

**Comment by HazCod** [comment]
Its not responding to M-HEAD from plex, thus plex marking it as dead.

**Comment by japaol** [comment]
Reducing interval time in 'sendAlive' from 300s to something smaller seems to work for me (i'm using 15s right now)

**Comment by HazCod** [comment]
Aha! Will try that tonight

**Comment by HazCod** [comment]
@japaol `touch test && go build main.go && ./main -playlist=test` with `aliveTick := time.Tick(15 * time.Second)` will not show telly in Plex. What did you do?

**Comment by japaol** [comment]
@HazCod I had to specify a UUID as device Id and a listen interface. I think i have not touch anything else.

**Comment by HazCod** [comment]
I tried with `go build main.go && ./main -playlist=test -listen=192.168.0.167:6077 -deviceid="2650EB7E-1768-4503-9FDA-E7377F3A640C"`.

**Comment by japaol** [comment]
@HazCod Mine is `./telly -logrequests -playlist Movistar.m3u -streams 99 -listen 192.168.1.98:6077 -deviceid a5288e73-409f-4191-b02d-2bf963433d7e`. I compiled `telly` with `make`, in `raspbian`.
I noticed that Windows shows `telly` as a multimedia device, in Networking, so it seems that SSDP is working well. My `Plex Media Server` is running on Windows.

**Comment by HazCod** [comment]
But did it pop up automatically when adding a new tuner under Plex?

**Comment by japaol** [comment]
I think i have managed to get it working.
Looking in another projects that emulates HDHomerun, like https://github.com/geertbongers/tvhProxy or https://github.com/TheJF/antennas, it seems that some models of HDHomerun uses its own discovery protocol on port 65001, and others models uses SSDP. So, changing the ModelNumber in the device.xml could make a change in Plex.
Furthermore, the DeviceID of the HDHomerun has to be a eigth char Id, but in SSDP we need a UUID.
So this is what i have do:
Changes in code:
- ModelNumber to `HDTC-2US`
- DeviceId fixed to `12345678`
- Reduce alive interval to `15s`
Run telly specifing a valid UUID as deviceId

With all of this, Plex detects telly at the first alive notification sent.

**Comment by HazCod** [comment]
@japaol can you try with this build? @tombowditch do you still have an IPTV subscription to test?

**Comment by tombowditch** [comment]
@HazCod I do, yes! :-)

**Comment by japaol** [comment]
It works, but I think that Plex search for the word `HDHomerun` in the `friendlyName` to detect it as a valid HDHomerun tuner.
In all tests I made, if I left the friendly name as default `telly`, Plex found nothing. But it I change to `telly HDHomerun` Plex starts to detect the tuner.

Note: between each tests, i had to restart Plex Media Server because sometime it gets stuck and says that no tuner available (i think that it is related to some internal timers or cache)

image

**Comment by HazCod** [comment]
Committed the change to the friendly name (I remember seeing this myself), will test tonight.

**Comment by HazCod** [comment]
Ok, so I finally got it to work if I restart Plex after adding telly!
@tombowditch can you test as wel? So we can merge,

image

**Comment by myusuf3** [comment]
I tested it! it works.

**Comment by HazCod** [comment]
@tombowditch I will go ahead and merge it, but will not release a new version. I'll leave that up to you.

**Comment by tombowditch** [comment]
All good! Many thanks for your work all. I will release a new version later today.

**Comment by HazCod** [comment]
Thanks Tom, and thank you for your input @japaol !

**Comment by myusuf3** [comment]
@HazCod how do you keep guides in sync, I have guide working for a couple of days then they get old. I am using p2.xml method. ideas?

**Pull request merged**
